# Generated by Django 4.1.1 on 2022-10-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_photo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('watcher', 'listing'), name='unique watcher-listing'),
        ),
    ]
