# Generated by Django 4.1.1 on 2022-10-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo',
            new_name='image_url',
        ),
    ]
